name: CI
on:
  pull_request:
    branches: [main]
  push:

jobs:
  test-accounts:
    runs-on: stackit-docker
    container: python:3.12
    steps:
      - run: |
          (git --version >/dev/null 2>&1) || (apt-get update -qq && apt-get install -y -qq git)
          git init -q .
          git remote add origin "https://${GITHUB_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git"
          git fetch -q --depth=1 origin "$GITHUB_SHA"
          git checkout -q FETCH_HEAD
      - run: cd accounts && pip install -e ../core -e .[dev] && pytest

  test-api:
    runs-on: stackit-docker
    container: python:3.12
    steps:
      - run: |
          (git --version >/dev/null 2>&1) || (apt-get update -qq && apt-get install -y -qq git)
          git init -q .
          git remote add origin "https://${GITHUB_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git"
          git fetch -q --depth=1 origin "$GITHUB_SHA"
          git checkout -q FETCH_HEAD
      - run: cd api && pip install -e ../core -e .[dev] && pytest

  test-chat:
    runs-on: stackit-docker
    container: python:3.12
    steps:
      - run: |
          (git --version >/dev/null 2>&1) || (apt-get update -qq && apt-get install -y -qq git)
          git init -q .
          git remote add origin "https://${GITHUB_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git"
          git fetch -q --depth=1 origin "$GITHUB_SHA"
          git checkout -q FETCH_HEAD
      - run: cd chat && pip install -e ../core -e .[dev] && pytest

  test-core:
    runs-on: stackit-docker
    container: python:3.12
    steps:
      - run: |
          (git --version >/dev/null 2>&1) || (apt-get update -qq && apt-get install -y -qq git)
          git init -q .
          git remote add origin "https://${GITHUB_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git"
          git fetch -q --depth=1 origin "$GITHUB_SHA"
          git checkout -q FETCH_HEAD
      - run: cd core && pip install -e .[dev] && pytest

  test-frontend:
    runs-on: stackit-docker
    container: node:20
    steps:
      - run: |
          (git --version >/dev/null 2>&1) || (apt-get update -qq && apt-get install -y -qq git)
          git init -q .
          git remote add origin "https://${GITHUB_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git"
          git fetch -q --depth=1 origin "$GITHUB_SHA"
          git checkout -q FETCH_HEAD
      - run: cd frontend && npm ci && npm test
